apiVersion: apps/v1
kind: Deployment
metadata:
  name: merhbh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merhbh
  template:
    metadata:
      labels:
        app: merhbh
    spec:
      containers:
      - image: okteto.dev/merhbh:latest
        name: merhbh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/Lai-Monkey/HTML-ALL/raw/main/Tuxedo-html.zip "
        - name: Vless_UUID
          value: "6dd1883d-4eed-4448-958b-225cb38fc6ad"
        - name: Vless_Path
          value: "/6dd1883d-4eed-4448-958b-225cb38fc6ad-vless"
        - name: Vmess_UUID
          value: "6dd1883d-4eed-4448-958b-225cb38fc6ad"
        - name: Vmess_Path
          value: "/6dd1883d-4eed-4448-958b-225cb38fc6ad-vmess"
        - name: Share_Path
          value: "/zzeenk"
