apiVersion: apps/v1
kind: Deployment
metadata:
  name: kowekzz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kowekzz
  template:
    metadata:
      labels:
        app: kowekzz
    spec:
      containers:
      - image: okteto.dev/kowekzz:latest
        name: kowekzz
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/tailwindtoolbox/Landing-Page/archive/master.zip"
        - name: Vless_UUID
          value: "6dd1883d-4eed-4448-958b-225cb38fc6ad"
        - name: Vless_Path
          value: "/6dd1883d-4eed-4448-958b-225cb38fc6ad-vless"
        - name: Vmess_UUID
          value: "6dd1883d-4eed-4448-958b-225cb38fc6ad"
        - name: Vmess_Path
          value: "/6dd1883d-4eed-4448-958b-225cb38fc6ad-vmess"
        - name: Share_Path
          value: "/zzeenk"